In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
pd.read_csv("d_regular_graphs.csv", index_col=0)

   d    V    E  m(G)  sol_status  b(G)       time
0  3   10   15     7           1   7.0   7.687367
1  3   20   30     7           1   7.0   2.604830
2  3   30   45     7           1   7.0   8.221211
3  3   40   60     7           1   7.0  13.935641
4  3   50   75     7           1   7.0   2.809740
5  3   60   90     7           1   7.0   9.420441
6  3   70  105     7           1   7.0   5.063549
7  3   80  120     7           1   7.0  16.385876
8  3   90  135     7           1   7.0  41.351617
9  3  100  150     7           1   7.0  16.881000

In [11]:
pd.read_csv("10_random_graph_with_20_vertices_31_12_2024_11_55.csv", index_col=0)

   d   V    E  m(G)  sol_status  b(G)        time
0  0  20   99    24           0   NaN   89.198758
1  1  20  102    24           0   NaN  112.743378
2  2  20   82    21           0   NaN   59.249567
3  3  20   92    23           0   NaN   80.636575
4  4  20   90    23           0   NaN  100.912382
5  5  20  101    25           0   NaN  112.051183
6  6  20   89    22           0   NaN   62.169371
7  7  20   88    21           0   NaN   59.836465
8  8  20   90    22           0   NaN   71.400338
9  9  20   99    24           0   NaN   87.469942

In [12]:
pd.read_csv("10_random_graph_with_20_vertices_6_1_2025_9_28.csv", index_col=0)

   d   V   E  m(G)  sol_status  b(G)       time
0  0  20  58    15           2   NaN  81.734786
1  1  20  55    16           2   NaN  89.650301
2  2  20  60    15           2   NaN  93.325374
3  3  20  51    14           2   NaN  99.030115
4  4  20  47    13           2   NaN  98.604806
5  5  20  47    14           2   NaN  97.941581
6  6  20  56    15           2   NaN  98.858278
7  7  20  56    15           2   NaN  96.937058
8  8  20  60    16           2   NaN  94.534599
9  9  20  66    18           0   NaN  77.934138

In [13]:
pd.read_csv("10_random_graph_with_20_vertices_6_1_2025_9_55.csv", index_col=0)

   d   V    E  m(G)  sol_status  b(G)        time
0  0  20  130    29           0   NaN  117.503207
1  1  20  136    30           0   NaN  152.875339
2  2  20  134    31           0   NaN  112.623037
3  3  20  131    30           0   NaN  110.648743
4  4  20  132    31           0   NaN  168.869192
5  5  20  127    29           0   NaN  108.882792
6  6  20  140    32           0   NaN  190.992515
7  7  20  137    31           0   NaN  114.039005
8  8  20  133    30           0   NaN  151.423624
9  9  20  123    29           0   NaN  153.602773

In [14]:
pd.read_csv("random_graphs_tests_ubuntu.csv", index_col=0)

    V      E  m(G) sol_status  b(G)  build_time  sol_time
0  10   21.9  11.4       0/10   0.0    0.157747       0.0
1  20   91.9  22.5       0/10   0.0    4.123039       0.0
2  30  217.5  34.7       0/10   0.0   35.131116       0.0

In [15]:
pd.read_csv("d_regular_graphs_ubuntu.csv", index_col=0)

      d    V       E  m(G) sol_status  b(G)        time
0     3   10    15.0     7      20/20  7.00    4.892479
1     3   20    30.0     7      20/20  7.00    5.674501
2     3   30    45.0     7      20/20  7.00    7.399788
3     3   40    60.0     7      20/20  7.00    6.759640
4     3   50    75.0     7      20/20  7.00    6.826895
5     3   60    90.0     7      20/20  7.00   14.117527
6     3   70   105.0     7      20/20  7.00   11.925806
7     3   80   120.0     7      20/20  7.00   14.298014
8     3   90   135.0     7      20/20  7.00   49.680710
9     3  100   150.0     7      20/20  7.00   18.601363
10    3  150   225.0     7      20/20  7.00   36.914386
11    4   10    20.0     9       5/20  2.25   27.852365
12    4   20    40.0     9      20/20  9.00   53.682148
13    4   30    60.0     9      20/20  9.00   85.428864
14    4   40    80.0     9      20/20  9.00  144.686813
15    4   50   100.0     9      18/20  8.10  235.096453
16    4   60   120.0     9      10/20  4.50  117.798922
17    4   70   140.0     9       7/20  3.15   99.918689
18    4   80   160.0     9      13/20  5.85  193.521832
19    4   90   180.0     9       7/20  3.15  117.165116
20    4  100   200.0     9      16/20  7.20  199.236344
21    4  150   300.0     9       8/20  3.60  109.646436
22    5   10    25.0    11       0/20  0.00    0.000000
23    5   20    50.0    11       5/20  2.75   61.694966
24    5   30    75.0    11       7/20  3.85  120.553781
25    5   40   100.0    11       0/20  0.00    0.000000
26    5   50   125.0    11       0/20  0.00    0.000000
27    5   60   150.0    11       0/20  0.00    0.000000
28    5   70   175.0    11       0/20  0.00    0.000000
29    5   80   200.0    11       0/20  0.00    0.000000
30    5   90   225.0    11       0/20  0.00    0.000000
31    5  100   250.0    11       0/20  0.00    0.000000
32    5  150   375.0    11       0/20  0.00    0.000000
33    6   10    30.0    13       0/20  0.00    0.000000
34    6   20    60.0    13       0/20  0.00    0.000000
35    6   30    90.0    13       0/20  0.00    0.000000
36    6   40   120.0    13       0/20  0.00    0.000000
37    6   50   150.0    13       0/20  0.00    0.000000
38    6   60   180.0    13       0/20  0.00    0.000000
39    6   70   210.0    13       0/20  0.00    0.000000
40    6   80   240.0    13       0/20  0.00    0.000000
41    6   90   270.0    13       0/20  0.00    0.000000
42    6  100   300.0    13       0/20  0.00    0.000000
43    6  150   450.0    13       0/20  0.00    0.000000
44    7   10    35.0    15       0/20  0.00    0.000000
45    7   20    70.0    15       0/20  0.00    0.000000
46    7   30   105.0    15       0/20  0.00    0.000000
47    7   40   140.0    15       0/20  0.00    0.000000
48    7   50   175.0    15       0/20  0.00    0.000000
49    7   60   210.0    15       0/20  0.00    0.000000
50    7   70   245.0    15       0/20  0.00    0.000000
51    7   80   280.0    15       0/20  0.00    0.000000
52    7   90   315.0    15       0/20  0.00    0.000000
53    7  100   350.0    15       0/20  0.00    0.000000
54    7  150   525.0    15       0/20  0.00    0.000000
55    8   10    40.0    17       0/20  0.00    0.000000
56    8   20    80.0    17       0/20  0.00    0.000000
57    8   30   120.0    17       0/20  0.00    0.000000
58    8   40   160.0    17       0/20  0.00    0.000000
59    8   50   200.0    17       0/20  0.00    0.000000
60    8   60   240.0    17       0/20  0.00    0.000000
61    8   70   280.0    17       0/20  0.00    0.000000
62    8   80   320.0    17       0/20  0.00    0.000000
63    8   90   360.0    17       0/20  0.00    0.000000
64    8  100   400.0    17       0/20  0.00    0.000000
65    8  150   600.0    17       0/20  0.00    0.000000
66    9   10    45.0    19       0/20  0.00    0.000000
67    9   20    90.0    19       0/20  0.00    0.000000
68    9   30   135.0    19       0/20  0.00    0.000000
69    9   40   180.0    19       0/20  0.00    0.000000
70    9   50   225.0    19       0/20  0.00    0.000000
71    9   60   270.0    19       0/20  0.00    0.000000
72    9   70   315.0    19       0/20  0.00    0.000000
73    9   80   360.0    19       0/20  0.00    0.000000
74    9   90   405.0    19       0/20  0.00    0.000000
75    9  100   450.0    19       0/20  0.00    0.000000
76    9  150   675.0    19       0/20  0.00    0.000000
77   10   20   100.0    21       0/20  0.00    0.000000
78   10   30   150.0    21       0/20  0.00    0.000000
79   10   40   200.0    21       0/20  0.00    0.000000
80   10   50   250.0    21       0/20  0.00    0.000000
81   10   60   300.0    21       0/20  0.00    0.000000
82   10   70   350.0    21       0/20  0.00    0.000000
83   10   80   400.0    21       0/20  0.00    0.000000
84   10   90   450.0    21       0/20  0.00    0.000000
85   10  100   500.0    21       0/20  0.00    0.000000
86   10  150   750.0    21       0/20  0.00    0.000000
87   11   20   110.0    23       0/20  0.00    0.000000
88   11   30   165.0    23       0/20  0.00    0.000000
89   11   40   220.0    23       0/20  0.00    0.000000
90   11   50   275.0    23       0/20  0.00    0.000000
91   11   60   330.0    23       0/20  0.00    0.000000
92   11   70   385.0    23       0/20  0.00    0.000000
93   11   80   440.0    23       0/20  0.00    0.000000
94   11   90   495.0    23       0/20  0.00    0.000000
95   11  100   550.0    23       0/20  0.00    0.000000
96   11  150   825.0    23       0/20  0.00    0.000000
97   12   20   120.0    25       0/20  0.00    0.000000
98   12   30   180.0    25       0/20  0.00    0.000000
99   12   40   240.0    25       0/20  0.00    0.000000
100  12   50   300.0    25       0/20  0.00    0.000000
101  12   60   360.0    25       0/20  0.00    0.000000
102  12   70   420.0    25       0/20  0.00    0.000000
103  12   80   480.0    25       0/20  0.00    0.000000
104  12   90   540.0    25       0/20  0.00    0.000000
105  12  100   600.0    25       0/20  0.00    0.000000
106  12  150   900.0    25       0/20  0.00    0.000000
107  13   20   130.0    27       0/20  0.00    0.000000
108  13   30   195.0    27       0/20  0.00    0.000000
109  13   40   260.0    27       0/20  0.00    0.000000
110  13   50   325.0    27       0/20  0.00    0.000000
111  13   60   390.0    27       0/20  0.00    0.000000
112  13   70   455.0    27       0/20  0.00    0.000000
113  13   80   520.0    27       0/20  0.00    0.000000
114  13   90   585.0    27       0/20  0.00    0.000000
115  13  100   650.0    27       0/20  0.00    0.000000
116  13  150   975.0    27       0/20  0.00    0.000000
117  14   20   140.0    29       0/20  0.00    0.000000
118  14   30   210.0    29       0/20  0.00    0.000000
119  14   40   280.0    29       0/20  0.00    0.000000
120  14   50   350.0    29       0/20  0.00    0.000000
121  14   60   420.0    29       0/20  0.00    0.000000
122  14   70   490.0    29       0/20  0.00    0.000000
123  14   80   560.0    29       0/20  0.00    0.000000
124  14   90   630.0    29       0/20  0.00    0.000000
125  14  100   700.0    29       0/20  0.00    0.000000
126  14  150  1050.0    29       0/20  0.00    0.000000
127  15   20   150.0    31       0/20  0.00    0.000000
128  15   30   225.0    31       0/20  0.00    0.000000
129  15   40   300.0    31       0/20  0.00    0.000000
130  15   50   375.0    31       0/20  0.00    0.000000
131  15   60   450.0    31       0/20  0.00    0.000000
132  15   70   525.0    31       0/20  0.00    0.000000
133  15   80   600.0    31       0/20  0.00    0.000000
134  15   90   675.0    31       0/20  0.00    0.000000
135  15  100   750.0    31       0/20  0.00    0.000000
136  15  150  1125.0    31       0/20  0.00    0.000000