In [1]:
import sys
sys.path.append("../../../src/b_chromatic")
sys.path.append("../../../src/b_chromatic/ipmodels")
import pulp as pl
import networkx as nx
import pandas as pd
from total_b_chromatic_model import find_total_b_chromatic_colouring
from utils import *
from m_degree import get_total_m_degree

In [5]:
MAX_TIME_LIMIT = 200

In [ ]:
G = nx.random_regular_graph(d=3,n=30)
V = list(G.nodes())
E = list(G.edges())
m = get_total_m_degree(G)

In [ ]:
sol_status, obj_value, time_taken, f, bchr_elements = find_total_b_chromatic_colouring(G, V, E, m, 20)
print(sol_status, obj_value, time_taken)

## Testing on random $d$-regular graphs

In [7]:
D = range(3, 6)
N = [10, 20, 30, 40, 50]
resultspd = {"d":[], "V": [], "E": [], "m(G)": [], "sol_status": [], "b(G)":[], "time": []}
for d in D:
    for n in N:
        if n > d:
            G = nx.random_regular_graph(d=d,n=n)
            V = list(G.nodes())
            E = list(G.edges())
            m = get_total_m_degree(G)
            sol_status, obj_value, time_taken, f, bchr_elements = find_total_b_chromatic_colouring(G, V, E, m, MAX_TIME_LIMIT)
            resultspd["d"].append(d)
            resultspd["V"].append(n)
            resultspd["E"].append(len(E))
            resultspd["m(G)"].append(m)
            resultspd["sol_status"].append(sol_status)
            resultspd["b(G)"].append(obj_value)
            resultspd["time"].append(time_taken)

In [8]:
pd.DataFrame(resultspd)

    d   V    E  m(G)  sol_status  b(G)        time
0   3  10   15     7           1   7.0    0.714721
1   3  20   30     7           1   7.0    1.727985
2   3  30   45     7           1   7.0    3.195118
3   3  40   60     7           1   7.0    3.728423
4   3  50   75     7           1   7.0    0.922686
5   4  10   20     9           2   NaN  199.789758
6   4  20   40     9           1   9.0   23.744836
7   4  30   60     9           1   9.0   91.131303
8   4  40   80     9           1   9.0   47.403824
9   4  50  100     9           2   NaN  193.874767
10  5  10   25    11           2   NaN  199.341121
11  5  20   50    11           2   NaN  198.548232
12  5  30   75    11           2   NaN  196.553859
13  5  40  100    11           1  11.0  121.094306
14  5  50  125    11           2   NaN  179.273242

In [4]:
pd.DataFrame(resultspd)

   d   V    E  m(G)  sol_status  b(G)       time
0  3  10   15     7           1   7.0  10.851767
1  3  20   30     7           1   7.0   1.533486
2  3  30   45     7           1   7.0   3.060192
3  3  40   60     7           1   7.0   3.198654
4  3  50   75     7           1   7.0   3.380457
5  4  10   20     9           2   NaN  99.758801
6  4  20   40     9           1   9.0  36.814788
7  4  30   60     9           2   NaN  99.200610
8  4  40   80     9           2   NaN  98.450754
9  4  50  100     9           2   NaN  96.005128

In [8]:
pd.DataFrame(resultspd)

    d   V    E  m(G)  sol_status  b(G)        time
0   3  10   15     7           1   7.0   10.941934
1   3  20   30     7           1   7.0    7.850236
2   3  30   45     7           1   7.0   12.618274
3   3  40   60     7           1   7.0    6.712435
4   3  50   75     7           1   7.0    2.554615
5   4  10   20     9           2   NaN   99.722654
6   4  20   40     9           1   9.0   38.152937
7   4  30   60     9           0   NaN   98.410670
8   4  40   80     9           0   NaN   95.310528
9   4  50  100     9           0   NaN   88.244605
10  5  10   25    11           0   NaN   99.255914
11  5  20   50    11           0   NaN   97.324598
12  5  30   75    11           0   NaN   94.963807
13  5  40  100    11           0   NaN   94.513661
14  5  50  125    11           0   NaN   82.427368
15  6  10   30    13           0   NaN   98.125883
16  6  20   60    13           0   NaN   94.586407
17  6  30   90    13           0   NaN   98.153832
18  6  40  120    13           0   NaN  102.263230
19  6  50  150    13           0   NaN  102.986794
20  7  10   35    15           0   NaN   97.384279
21  7  20   70    15           0   NaN   86.600363
22  7  30  105    15           0   NaN   70.074412
23  7  40  140    15           0   NaN  113.249507
24  7  50  175    15           0   NaN  136.029272
25  8  10   40    17           0   NaN   95.279273
26  8  20   80    17           0   NaN  101.674281
27  8  30  120    17           0   NaN  102.619826
28  8  40  160    17           0   NaN  125.684864
29  8  50  200    17           0   NaN  119.152272
30  9  10   45    19           0   NaN   82.599844
31  9  20   90    19           0   NaN   77.871640
32  9  30  135    19           0   NaN  127.593652
33  9  40  180    19           0   NaN  120.704719
34  9  50  225    19           0   NaN  180.221927